/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingland.vistas;

import java.awt.Color;

/**
 *
 * @author exopa
 */
public class Vista_Historial extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Historial
     */
    public Vista_Historial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usuarioBtn = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JLabel();
        placaBtn = new javax.swing.JPanel();
        placaTxt = new javax.swing.JLabel();
        ingresoBtn = new javax.swing.JPanel();
        ingresoTxt = new javax.swing.JLabel();
        opBtn = new javax.swing.JPanel();
        opTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioBtn.setBackground(new java.awt.Color(255, 255, 255));

        usuarioTxt.setBackground(new java.awt.Color(51, 51, 255));
        usuarioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingland/assent/user.png"))); // NOI18N
        usuarioTxt.setText("USUARIO");
        usuarioTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuarioTxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                usuarioTxtAncestorRemoved(evt);
            }
        });
        usuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuarioTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuarioTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout usuarioBtnLayout = new javax.swing.GroupLayout(usuarioBtn);
        usuarioBtn.setLayout(usuarioBtnLayout);
        usuarioBtnLayout.setHorizontalGroup(
            usuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        usuarioBtnLayout.setVerticalGroup(
            usuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(usuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 60));

        placaBtn.setBackground(new java.awt.Color(255, 255, 255));

        placaTxt.setBackground(new java.awt.Color(51, 51, 255));
        placaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placaTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingland/assent/sports-car.png"))); // NOI18N
        placaTxt.setText("PLACA");
        placaTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        placaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                placaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                placaTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout placaBtnLayout = new javax.swing.GroupLayout(placaBtn);
        placaBtn.setLayout(placaBtnLayout);
        placaBtnLayout.setHorizontalGroup(
            placaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(placaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        placaBtnLayout.setVerticalGroup(
            placaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(placaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(placaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 60));

        ingresoBtn.setBackground(new java.awt.Color(255, 255, 255));

        ingresoTxt.setBackground(new java.awt.Color(51, 51, 255));
        ingresoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingland/assent/history.png"))); // NOI18N
        ingresoTxt.setText("INGRESOS");
        ingresoTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ingresoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresoTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresoTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresoBtnLayout = new javax.swing.GroupLayout(ingresoBtn);
        ingresoBtn.setLayout(ingresoBtnLayout);
        ingresoBtnLayout.setHorizontalGroup(
            ingresoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        ingresoBtnLayout.setVerticalGroup(
            ingresoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(ingresoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 60));

        opBtn.setBackground(new java.awt.Color(255, 255, 255));

        opTxt.setBackground(new java.awt.Color(51, 51, 255));
        opTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingland/assent/management.png"))); // NOI18N
        opTxt.setText("OP X DIA");
        opTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout opBtnLayout = new javax.swing.GroupLayout(opBtn);
        opBtn.setLayout(opBtnLayout);
        opBtnLayout.setHorizontalGroup(
            opBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opBtnLayout.createSequentialGroup()
                .addComponent(opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        opBtnLayout.setVerticalGroup(
            opBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(opBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 60));

        jScrollPane1.setBackground(new java.awt.Color(51, 102, 255));

        jTable1.setBackground(new java.awt.Color(51, 102, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Placa", "Modelo", "Fecha Entrada", "Fecha Salida", "Valor pagado"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 480, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingland/assent/design.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTxtAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usuarioTxtAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtAncestorRemoved

    private void usuarioTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTxtMouseEntered
        usuarioBtn.setBackground(Color.red);
    }//GEN-LAST:event_usuarioTxtMouseEntered

    private void usuarioTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTxtMouseExited
        usuarioBtn.setBackground(Color.white);
    }//GEN-LAST:event_usuarioTxtMouseExited

    private void placaTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placaTxtMouseEntered
        placaBtn.setBackground(Color.red);
    }//GEN-LAST:event_placaTxtMouseEntered

    private void placaTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placaTxtMouseExited
        placaBtn.setBackground(Color.white);
    }//GEN-LAST:event_placaTxtMouseExited

    private void ingresoTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoTxtMouseEntered
        ingresoBtn.setBackground(Color.red);
    }//GEN-LAST:event_ingresoTxtMouseEntered

    private void ingresoTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoTxtMouseExited
        ingresoBtn.setBackground(Color.white);
    }//GEN-LAST:event_ingresoTxtMouseExited

    private void opTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opTxtMouseEntered
        opBtn.setBackground(Color.red);
    }//GEN-LAST:event_opTxtMouseEntered

    private void opTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opTxtMouseExited
       opBtn.setBackground(Color.white);
    }//GEN-LAST:event_opTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ingresoBtn;
    private javax.swing.JLabel ingresoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel opBtn;
    private javax.swing.JLabel opTxt;
    private javax.swing.JPanel placaBtn;
    private javax.swing.JLabel placaTxt;
    private javax.swing.JPanel usuarioBtn;
    private javax.swing.JLabel usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
